# SPDX-FileCopyrightText: Copyright (c) 2025 Massachusetts Institute of Technology
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Derived from:
#   https://gitlab.com/nvidia/container-images/l4t-jetpack/-/blob/master/Dockerfile.jetpack_6
#

#################################################################
# Build Stage
#################################################################

ARG GPU_TYPE=igpu
ARG HOLOSCAN_VERSION=3.2.0
ARG HOLOSCAN_BASE_IMAGE=nvcr.io/nvidia/clara-holoscan/holoscan:v${HOLOSCAN_VERSION}-${GPU_TYPE}
FROM ${HOLOSCAN_BASE_IMAGE} AS build

ARG DEBIAN_FRONTEND=noninteractive

#
# Configure cmake repo
#
ADD --chmod=664 https://apt.kitware.com/keys/kitware-archive-latest.asc /etc/apt/trusted.gpg.d/
RUN echo "deb https://apt.kitware.com/ubuntu/ $(cat /etc/os-release | grep -Po '^UBUNTU_CODENAME=\K[^ ]*') main" >> /etc/apt/sources.list.d/kitware.list

# workaround for dpkg-shlibdeps needing to locate libcuda.so.1 and assign it to a package for dependency generation
RUN ln -s /usr/local/cuda/targets/aarch64-linux/lib/stubs/libcuda.so /usr/lib/libcuda.so.1

#
# Install dependencies
#
RUN apt-get update && apt-get install -y --no-install-recommends \
        cmake=3.26.* \
        cmake-data=3.26.* \
        file \
        libhdf5-dev \
    && rm /usr/local/bin/cmake /usr/local/bin/cpack

#
# Build other dependencies
#
RUN apt-get install -y --no-install-recommends \
        libbpf-dev \
        libelf-dev \
        libibverbs-dev \
        libpcap0.8-dev \
        libssl-dev \
        meson \
        pkgconf \
        python3-pyelftools \
        zlib1g
ADD https://github.com/ryanvolz/dpdk-stable.git#24.11-jetson /dpdk
WORKDIR /dpdk
RUN meson build \
        -Dc_args=-I/usr/local/cuda/include \
        -Dplatform=jetsonorin \
        -Dexamples=ethtool \
        -Ddisable_drivers=baseband/*,bus/ifpga/*,common/cpt,common/cnxk,common/dpaax,common/iavf,common/octeontx,common/octeontx2,crypto/nitrox,event/cnxk,net/ark,net/atlantic,net/avp,net/axgbe,net/bnx2x,net/bnxt,net/cnxk,net/cxgbe,net/e1000,net/ena,net/enic,net/fm10k,net/hinic,net/hns3,net/i40e,vdpa/ifc,net/igc,net/liquidio,net/netvsc,net/nfp,net/qede,net/sfc,net/thunderx,net/vdev_netvsc,net/vmxnet3,regex/octeontx2 \
    && ninja -C build \
    && ninja -C build install \
    && ldconfig

#
# Build holoscan-rf-array
ARG BUILD_CUDA_ARCHITECTURES=87
WORKDIR /holohub
COPY . .
ENV HOLOHUB_CMAKE_ARGS="-DCMAKE_CUDA_ARCHITECTURES=${BUILD_CUDA_ARCHITECTURES} -DCMAKE_VERBOSE_MAKEFILE=ON -DANO_MGR='dpdk' -DHOLOHUB_DOWNLOAD_DATASETS=OFF"

RUN ./run build holoscan-rf-array --buildpath build \
    --configure-args "${HOLOHUB_CMAKE_ARGS}" \
    --type release \
    --parallel 4

#################################################################
# Runtime Image Stage
#################################################################

FROM nvcr.io/nvidia/base/ubuntu:22.04_20240212 AS run

LABEL org.opencontainers.image.description="Holoscan RF array operators"

#
# Install any utils needed for execution
#
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gpg \
    libnuma1 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

#
# Configure nvidia apt repo
#
ARG JETPACK_RELEASE=r36.4
ADD --chmod=664 https://repo.download.nvidia.com/jetson/jetson-ota-public.asc /etc/apt/trusted.gpg.d/
ADD --chmod=664 https://repo.download.nvidia.com/jetson/nvidia-repo-pin-600 /etc/apt/preferences.d/
RUN echo "deb https://repo.download.nvidia.com/jetson/common ${JETPACK_RELEASE} main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list

#
# Setup DOCA APT repository
#
# (version is what was used for the holoscan version that we are using)
ARG DOCA_VERSION=2.8.0
RUN DOCA_ARCH=$(uname -m); \
    if [ "${DOCA_ARCH}" = "aarch64" ]; then \
        DOCA_ARCH="arm64-sbsa"; \
    fi \
    && DOCA_REPO_ROOT="https://linux.mellanox.com/public/repo/doca" \
    && DOCA_HOSTNAME=$(echo "${DOCA_REPO_ROOT}" | sed 's|https://\([^/]*\).*|\1|') \
    && DISTRO=$(. /etc/os-release && echo "$ID$VERSION_ID") \
    && DOCA_URL="${DOCA_REPO_ROOT}/${DOCA_VERSION}/${DISTRO}/${DOCA_ARCH}/" \
    && DOCA_GPG_KEY="GPG-KEY-Mellanox.pub" \
    && DOCA_GPG_KEY_PATH="/etc/apt/trusted.gpg.d/${DOCA_GPG_KEY}" \
    && curl -fsSL ${DOCA_URL}/${DOCA_GPG_KEY} | gpg --dearmor -o ${DOCA_GPG_KEY_PATH} \
    && echo "deb [signed-by=${DOCA_GPG_KEY_PATH}] ${DOCA_URL} ./" \
        > /etc/apt/sources.list.d/doca.list \
    && DOCA_HOSTNAME=$(echo "${DOCA_REPO_ROOT}" | sed 's|https://\([^/]*\).*|\1|') \
    && echo "Package: *\nPin: origin \"${DOCA_HOSTNAME}\"\nPin-Priority: 800" \
        > /etc/apt/preferences.d/doca-pin

#
# Install rf-array dependencies and needed cuda stuff
# (do this before holoscan because it shouldn't change as often)
#
ARG HOLOSCAN_VERSION
ARG CUDA_VERSION_STRING=12-6
RUN apt-get update && apt-get install -y --no-install-recommends \
    holoscan=${HOLOSCAN_VERSION}* \
    python3-numpy \
    python3-scipy \
    cuda-nvrtc-${CUDA_VERSION_STRING} \
    libcublas-${CUDA_VERSION_STRING} \
    libcufft-${CUDA_VERSION_STRING} \
    libcurand-${CUDA_VERSION_STRING} \
    libcusolver-${CUDA_VERSION_STRING} \
    libnvjitlink-${CUDA_VERSION_STRING} \
    ibverbs-providers \
    libbpf0 \
    libelf1 \
    libibverbs1 \
    libnuma1 \
    libpcap0.8 \
    libssl3 \
    zlib1g \
    && apt-get download cuda-compat-${CUDA_VERSION_STRING} \
    && dpkg-deb -R ./cuda-compat-${CUDA_VERSION_STRING}_*_arm64.deb ./cuda-compat \
    && cp -r ./cuda-compat/usr/local/* /usr/local/ \
    && rm -rf ./cuda-compat-${CUDA_VERSION_STRING}_*_arm64.deb ./cuda-compat \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

#
# Install Python dependencies not covered by deb packages
#
RUN python3 -m pip install --no-cache-dir holoscan==${HOLOSCAN_VERSION} numpy==1.26 cupy-cuda12x scipy==1.15

#
# Install DPDK libraries from build stage
#
# Use bind mount and cp command to preserve symlinks (which COPY does not do)
RUN --mount=type=bind,from=build,source=/usr/local/lib/aarch64-linux-gnu,target=/build/lib \
    mkdir -p /usr/local/lib/aarch64-linux-gnu \
    && cp -a /build/lib/librte_* /build/lib/dpdk /usr/local/lib/aarch64-linux-gnu

#
# Install holoscan-rf-array
#
ARG RF_ARRAY_PACKAGE=holoscan-rf-array_*.deb
RUN --mount=type=bind,from=build,target=/tmp/build-stage \
    apt-get update \
    && dpkg --unpack /tmp/build-stage/holohub/${RF_ARRAY_PACKAGE} \
    && apt-get install -f -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN ldconfig

#
# Set up environment variables
#
ENV CUDA_HOME="/usr/local/cuda"
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64"

ENV NVIDIA_VISIBLE_DEVICES="all"
ENV NVIDIA_DRIVER_CAPABILITIES="all"

ENV PYTHONPATH="/opt/nvidia/holoscan/python/lib"
