version: "3"
services:
  mep_recorder:
    image: ghcr.io/ryanvolz/holohub/mep-recorder:rf_array
    container_name: mep_recorder
    env_file: .env
    environment:
      - HOLOSCAN_EXECUTOR_LOG_LEVEL=WARN
      - HOLOSCAN_LOG_LEVEL=INFO
      - HOLOSCAN_LOG_FORMAT=DEFAULT
    networks:
      - rfsoc_10GbE
    ports:
      - 60133:60133/udp
    profiles:
      - recording
    restart: unless-stopped
    runtime: nvidia
    tmpfs:
      - /ramdisk:mode=777,uid=${UID},gid=${GID},nodev,nosuid,noexec,size=1G
    user: ${UID}:${GID}
    volumes:
      - /data/ringbuffer:/data/ringbuffer

networks:
  rfsoc_10GbE:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "192.168.4.1"
      com.docker.network.driver.mtu: 9000
