name: Build Holoscan RF array deb package

on:
  workflow_dispatch:
  push:
    tags:
      - "rf-array-*"
  pull_request:
    branches:
      - "rf_array"

env:
  BUILD_CUDA_KEYRING: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
  DOCKER_REGISTRY: ghcr.io
  HOLOSCAN_VERSION: 3.4.0
  DOCA_VERSION: 2.9.3

jobs:
  build_holoscan_rf_array_deb:
    name: "Build holoscan-rf-array deb package"
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CUDA DEB repo
        run: |
          wget ${{ env.BUILD_CUDA_KEYRING }}
          sudo dpkg -i cuda-keyring_*.deb
          sudo apt-get update
      - name: Set up DOCA DEB repo
        run: |
          export BASE_URL="https://linux.mellanox.com/public/repo/doca"
          export DOCA_URL="$BASE_URL/${{ env.DOCA_VERSION }}/ubuntu22.04/arm64-sbsa/"
          curl $BASE_URL/GPG-KEY-Mellanox.pub | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/GPG-KEY-Mellanox.pub
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/GPG-KEY-Mellanox.pub] $DOCA_URL ./" | sudo tee /etc/apt/sources.list.d/doca.list
          sudo apt-get update
      - name: Install dependencies
        run: |
          sudo apt-get install -y cuda-toolkit holoscan=${{ env.HOLOSCAN_VERSION }}* libhdf5-dev
      - name: Checkout dpdk
        uses: actions/checkout@v4
        with:
          repository: "ryanvolz/dpdk-stable"
          ref: 24.11-jetson
          path: "dpdk"
      - name: Build dpdk DEB package
        run: |
          sudo apt-get install -y debhelper build-essential dh-make chrpath libbpf-dev libelf-dev libibverbs-dev libnuma-dev libpcap0.8-dev meson pkgconf python3-pyelftools
          pushd dpdk
          DEB_BUILD_OPTIONS="nocheck noautodbgsym" dpkg-buildpackage -us -uc -b
          popd
          sudo dpkg -i dpdk-for-jetson_*.deb
      - name: Checkout holoscan
        uses: actions/checkout@v4
        with:
          repository: "nvidia-holoscan/holoscan-sdk"
          ref: v${{ env.HOLOSCAN_VERSION }}
          path: "holoscan-sdk"
      - name: Copy Holoscan python headers
        # workaround for Holoscan deb package not including Python headers
        run: |
          sudo mkdir -p /opt/nvidia/holoscan/include/holoscan/python/core
          sudo cp -a holoscan-sdk/python/holoscan/core/*.hpp /opt/nvidia/holoscan/include/holoscan/python/core/
      - name: Make libcuda.so.1 symlink
        # workaround for dpkg-shlibdeps needing to locate libcuda.so.1 and assign it to a package for dependency generation
        run: |
          sudo ln -s /usr/local/cuda/targets/aarch64-linux/lib/stubs/libcuda.so /usr/lib/libcuda.so.1
      - name: Run build
        run: |
          ./run build holoscan-rf-array --buildpath build --configure-args "-DCMAKE_CUDA_ARCHITECTURES=87 -DCMAKE_VERBOSE_MAKEFILE=ON -DANO_MGR='dpdk' -DHOLOHUB_DOWNLOAD_DATASETS=OFF" --type release --parallel 4
      - name: Upload DEB package artifact
        uses: actions/upload-artifact@v4
        with:
          name: holoscan-rf-array-deb
          path: |
            dpdk-for-jetson_*.deb
            holoscan-rf-array_*.deb
          if-no-files-found: error
