name: Build Holoscan RF array package and Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'rf_array'
    tags:
      - 'rf-array-*'
  pull_request:
    branches:
      - 'rf_array'

env:
  BUILD_CUDA_KEYRING: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
  BUILD_HOLOSCAN_VERSION: 2.5.0.1-1
  DOCKER_REGISTRY: ghcr.io
  IMAGE_CONTEXT: pkg/holoscan-rf-array
  IMAGE_DOCKERFILE: pkg/holoscan-rf-array/Dockerfile.jetsonorin
  IMAGE_NAME: ${{ github.repository }}/rf-array
  IMAGE_JETPACK_RELEASE: r36.3
  IMAGE_CUDA_VERSION_STRING: 12-2
  IMAGE_RF_ARRAY_PACKAGE: holoscan-rf-array_*.deb

jobs:
  build_holoscan_rf_array:
    name: "Build holoscan-rf-array"
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CUDA DEB repo
        run: |
          wget ${{ env.BUILD_CUDA_KEYRING }}
          sudo dpkg -i cuda-keyring_*.deb
          sudo apt-get update
      - name: Install dependencies
        run: |
          sudo apt-get install -y cuda-toolkit holoscan=${{ env.BUILD_HOLOSCAN_VERSION }} libhdf5-dev
      - name: Run build
        run: |
          ./run build holoscan-rf-array --buildpath build --configure-args "-DCMAKE_CUDA_ARCHITECTURES=87 -DCMAKE_VERBOSE_MAKEFILE=OFF -DHOLOHUB_DOWNLOAD_DATASETS=OFF" --type release
      - name: Upload DEB package artifact
        uses: actions/upload-artifact@v4
        with:
          name: holoscan-rf-array-deb
          path: holoscan-rf-array_*.deb
  build_docker_image:
    name: "Build rf-array docker image for Jetson Orin"
    needs: build_holoscan_rf_array
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download holoscan-rf-array DEB package artifact
        uses: actions/download-artifact@v4
        with:
          name: holoscan-rf-array-deb
          path: ${{ env.IMAGE_CONTEXT }}
      - name: Log in to the NVIDIA container registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: $oauthtoken
          password: ${{ secrets.NGC_API_KEY }}
      - name: Log in to the upload container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.description=Holoscan MEP recorder
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=match,pattern=rf-array-(.*),group=1
            type=match,pattern=rf-array-(v\d+.\d+).*,group=1
            type=match,pattern=rf-array-(v\d+).*,group=1
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.IMAGE_CONTEXT }}
          file: ${{ env.IMAGE_DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: RELEASE=${{ env.IMAGE_JETPACK_RELEASE }}
            CUDA_VERSION_STRING=${{ env.IMAGE_CUDA_VERSION_STRING }}
            RF_ARRAY_PACKAGE=${{ env.IMAGE_RF_ARRAY_PACKAGE }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
